# Heading 1
 Test the installation
 
 

In [1]:
print "hello !!"

hello !!


In [1]:
print("test")

test


In [2]:
x = 5


In [3]:
for i in range(0,5):
    print("i={0} x={1}".format(i,x))
    


i=0 x=5
i=1 x=5
i=2 x=5
i=3 x=5
i=4 x=5


In [2]:
import matplotlib.pyplot as plt


In [5]:
import numpy as np


In [6]:
np_height = np.array([150,167, 180, 140])
np_weight = np.array([130,120, 190, 160])


In [7]:
bmi = np_weight/ np_height ** 2

In [8]:
print(bmi)

[ 0.00577778  0.00430277  0.0058642   0.00816327]


In [9]:
print(bmi[bmi>0.005])

[ 0.00577778  0.0058642   0.00816327]


In [10]:
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

In [11]:
np_baseball = np.array(baseball)

In [12]:
print(np_baseball.shape)

(4, 2)


In [15]:
print(type(np_baseball))

<class 'numpy.ndarray'>


In [17]:
# third row player stats
print(np_baseball[2,:])

[ 210.    98.5]


In [18]:
#entire 2nd column of weights
print(np_baseball[:,1])

[  78.4  102.7   98.5   75.2]


In [19]:
#height of 4th player
print(np_baseball[3,0])


188.0


In [20]:
#mean height
print(np.mean(np_baseball[:,0]))

198.25


In [21]:
#median height
print(np.median(np_baseball))

141.35


In [22]:
#find standard deviation
print(np.std(np_baseball))

56.3909733468
